### ISSUE TITLE
Remove generic type hints to support version < Python-3.9

### ISSUE THREAD

**Issue by Pankul94** [konidev20/pyshamir#29]
Hi there

`combine` and `split` method in pyshamir have generic type hints `list[bytearray]`, I am running into an error when using this on Python3.8 interpreter: 
```
def combine(parts: list[bytearray]) -> bytearray:
TypeError: 'type' object is not subscriptable
```
I think this is because the generic type hints were introduced in [Python 3.9](https://docs.python.org/3.9/library/typing.html#building-generic-types)

I can make the source code change myself but dont want to deviate from upstream. Would you consider removing the type hints to support Python version < 3.9? 

Let me know if you are fine with removing them and I can send out a PR for the same. Please let me know if there is a way to go around the issue without making a code change.

**Comment by Pankul94** [comment]
https://github.com/konidev20/pyshamir/pull/30

**Comment by konidev20** [comment]
Hey @Pankul94, 

I will push a new release once the pipe has passed. 

Thanks.
